"""Updated Location/Zip model

Revision ID: 0824e0926cda
Revises: 551ac9488fa4
Create Date: 2025-03-29 16:32:40.841078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0824e0926cda'
down_revision: Union[str, None] = '551ac9488fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First make the column nullable
    op.execute("ALTER TABLE zip_codes ALTER COLUMN plus4 DROP NOT NULL;")
    
    # Then change the type with proper USING clause
    op.execute("ALTER TABLE zip_codes ALTER COLUMN plus4 TYPE INTEGER USING (plus4::integer);")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First handle NULL values by setting them to 0
    op.execute("UPDATE zip_codes SET plus4 = 0 WHERE plus4 IS NULL;")
    
    # Then change type back to BOOLEAN with proper USING clause
    op.execute("ALTER TABLE zip_codes ALTER COLUMN plus4 TYPE BOOLEAN USING (CASE WHEN plus4 = 0 THEN FALSE ELSE TRUE END);")
    
    # Finally make it NOT NULL again
    op.execute("ALTER TABLE zip_codes ALTER COLUMN plus4 SET NOT NULL;")
    # ### end Alembic commands ###
