"""modify relationships of joins models

Revision ID: 0887bfbee033
Revises: 0986c6fb0b27
Create Date: 2025-03-28 13:22:56.572608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0887bfbee033'
down_revision: Union[str, None] = '0986c6fb0b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_business_contacts_id', table_name='business_contacts')
    op.drop_index('ix_business_sources_id', table_name='business_sources')
    op.drop_index('ix_source_contacts_id', table_name='source_contacts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_source_contacts_id', 'source_contacts', ['id'], unique=False)
    op.create_index('ix_business_sources_id', 'business_sources', ['id'], unique=False)
    op.create_index('ix_business_contacts_id', 'business_contacts', ['id'], unique=False)
    # ### end Alembic commands ###
