"""Added google cid to zipcode model

Revision ID: 6365a7471d7b
Revises: 0824e0926cda
Create Date: 2025-03-29 18:04:48.372982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6365a7471d7b'
down_revision: Union[str, None] = '0824e0926cda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zip_codes', sa.Column('google_cid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zip_codes', 'google_cid')
    # ### end Alembic commands ###
