"""Initial migration

Revision ID: 6ff6d58b0557
Revises: 
Create Date: 2025-03-22 11:30:34.504261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ff6d58b0557'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('business_contacts_contact_id_fkey', 'business_contacts', type_='foreignkey')
    op.drop_constraint('business_contacts_business_id_fkey', 'business_contacts', type_='foreignkey')
    op.create_foreign_key(None, 'business_contacts', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key(None, 'business_contacts', 'contacts', ['contact_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'business_contacts', type_='foreignkey')
    op.drop_constraint(None, 'business_contacts', type_='foreignkey')
    op.create_foreign_key('business_contacts_business_id_fkey', 'business_contacts', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('business_contacts_contact_id_fkey', 'business_contacts', 'contacts', ['contact_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
