"""Add Business models and revise Source and Contact models

Revision ID: b97abdedbb94
Revises: 6ff6d58b0557
Create Date: 2025-03-22 22:07:13.865391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b97abdedbb94'
down_revision: Union[str, None] = '6ff6d58b0557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_sources',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('business_id', 'source_id')
    )
    op.create_table('source_contacts',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('source_id', 'contact_id')
    )
    op.add_column('businesses', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('businesses', sa.Column('address2', sa.String(length=255), nullable=True))
    op.add_column('businesses', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('businesses', sa.Column('state', sa.String(length=255), nullable=True))
    op.add_column('businesses', sa.Column('zip', sa.String(length=20), nullable=True))
    op.add_column('businesses', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('businesses', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('businesses', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('businesses', sa.Column('notes', sa.String(), nullable=True))
    op.drop_column('businesses', 'location')
    op.add_column('contacts', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('sources', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'notes')
    op.drop_column('contacts', 'notes')
    op.add_column('businesses', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('businesses', 'notes')
    op.drop_column('businesses', 'email')
    op.drop_column('businesses', 'website')
    op.drop_column('businesses', 'phone')
    op.drop_column('businesses', 'zip')
    op.drop_column('businesses', 'state')
    op.drop_column('businesses', 'city')
    op.drop_column('businesses', 'address2')
    op.drop_column('businesses', 'address')
    op.drop_table('source_contacts')
    op.drop_table('business_sources')
    # ### end Alembic commands ###
