"""Modify Business Model to include created and updated stamps

Revision ID: e32ed1fc924a
Revises: 6365a7471d7b
Create Date: 2025-04-04 20:54:27.120826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32ed1fc924a'
down_revision: Union[str, None] = '6365a7471d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('businesses', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'updated')
    op.drop_column('businesses', 'created')
    # ### end Alembic commands ###
